name: CMake on a single platform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Conan
        uses: jwidauer/setup-conan@v1

      - name: Set up Clang v18
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18 all

      - name: Print Environment Details
        run: |
          echo ${{github.workspace}}
          echo ${{env.BUILD_TYPE}}
          which clang-18
          which clang++-18
          conan --version
          cmake --version

      - name: Resolve Conan Dependencies and Configure CMake
        working-directory: ${{github.workspace}}
        run: ./bin/init-cmake-build.sh ${{env.BUILD_TYPE}}

      - name: Build
        working-directory: ${{github.workspace}}
        run: ./bin/run-scan-build.sh

      - name: Test
        working-directory: ${{github.workspace}}
        run: cmake --build ./build --target test
