# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Conan
        uses: jwidauer/setup-conan@v1

      - name: Set up Clang
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get install -y clang-18 lldb-18 lld-18
          sudo apt-get install -y libllvm-18-ocaml-dev libllvm18 llvm-18 llvm-18-dev llvm-18-doc llvm-18-runtime

      - name: Print Details
        run: |
          echo ${{github.workspace}}
          echo ${{env.BUILD_TYPE}}
          clang --version
          clang++ --version
          conan --version
          cmake --version

      - name: Configure Conan and CMake
        working-directory: ${{github.workspace}}
        run: ./bin/init-cmake-build.sh ${{env.BUILD_TYPE}}

      - name: Build
        working-directory: ${{github.workspace}}
        run: ./bin/run-scan-build.sh

      - name: Test
        working-directory: ${{github.workspace}}
        run: cmake --build ./build --target test
